### ISSUE TITLE
Evaluate new Fvalues [for improveModelNfp() and ChooseAndReplacePoint()]

### ISSUE THREAD

**Issue by thiagolims** [iocenter/FieldOpt-Research#20]
Implement method evaluateNewFvalues() which computes the function values for a set of new points of interest.

**Comment by thiagolims** [comment]
Hey Mathias(@Bellout), have you tested evaluateNewFvalues() ?

**Comment by Bellout** [comment]
@thiagolims: I took away the whole function evaluateNewFvalues() b/c it was an extra layer in the interaction of improveNfp with iterate(). But I might have to bring it back since this functionality is probably used other places. Yes, now that I think of it... Also, once it is an standalone function, I need to develop a test just for this function. I haven't really tested it since it comes after NewPoint() which is not done yet. We can discuss more afterwards. Cheers.

**Comment by Bellout** [comment]
We need to re-create the function evaluateNewFvalues() and put the code currently only in improveModelNfp() into that function. This way both improveModelNfp and chooseAndReplacePoint() can use the same code in evaluateNewFvalues().

**Comment by thiagolims** [comment]
Good idea, @Bellout  ! I was about to suggest that. Besides, I think there might be other parts of the code in the future that would need to invoke evaluateNewFvalues()

**Comment by Bellout** [comment]
Indeed. In the meantime, i.e., if I don't get to do this before you need it to continue with iterate(), then we (you) should just copy the code/setup from improveModelNfp into chooseAndReplacePoint(), just to have the latter up and running. This will also make the encompassing function ensureImprovement() ready/finished. We (I) can fixe the double-code in evaluateNewFvalues() later on (soon).

**Comment by thiagolims** [comment]
See commit: 6216742f28a5ad0e1849fb5d0a7dccf88be55f87
